#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} worker secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

WORKER="vineyard-scheduler"
DOMAIN="beachroad.casa"
ADMIN_EMAIL="shumanj1224@gmail.com"

# put_worker_secret NAME VALUE — store a secret on the Cloudflare worker via
# wrangler (the repo's production deployment). Falls back to a warning with
# the exact manual command.
put_worker_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | npx --yes wrangler secret put "$name" --name "$WORKER" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s worker secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Worker secret $name (run: echo \"<value>\" | npx wrangler secret put $name --name $WORKER)")
    warn "couldn't set worker secret $name — wrangler not authenticated? Set it manually later."
  fi
}

TOTAL_STAGES=6

banner "Resend email setup — $WORKER"

# ── Stage 1: Resend account ───────────────────────────────────────────────
stage "Resend — account"
say "The scheduler sends its admin notifications through Resend."
say "First make sure you're logged in (account email is where test sends"
say "from onboarding@resend.dev are allowed, so use your usual one)."
open_url "https://resend.com/login"
step "Log in — or click Sign up and create an account if you don't have one."
note "A free account is enough: 100 emails/day, 3,000/month."
pause "Logged in to Resend?"

# ── Stage 2: Domain verification ──────────────────────────────────────────
stage "Resend — verify your domain ($DOMAIN)"
say "Without a verified domain, Resend only lets you send FROM"
say "'onboarding@resend.dev' and ONLY to your own account's email —"
say "notifications to $ADMIN_EMAIL would fail. Verifying the domain"
say "removes that restriction and makes email reliable."
if confirm "Verify $DOMAIN now? (recommended)"; then
  open_url "https://resend.com/domains"
  step "In Resend: Domains → 'Add Domain' → enter '$DOMAIN' → Add."
  step "Resend shows a table of DNS records (DKIM, SPF, DMARC...)."
  step "Keep this tab open — you'll copy each record next."
  open_url "https://dash.cloudflare.com"
  step "In Cloudflare: pick the '$DOMAIN' zone → DNS → Records → Add record."
  step "For EACH record Resend showed: match its Type, Name, and Value."
  note "MX/TXT records: leave Proxy off (DNS only / grey cloud) — Resend"
  note "needs to read them directly. Resend's docs link is on that page."
  open_url "https://resend.com/docs/dashboard/domains/introduction"
  step "When added, back in Resend click 'Verify' (propagation may take a"
  step "few minutes — the status flips to 'Verified')."
  pause "Domain shows 'Verified' in Resend?"
  DOMAIN_VERIFIED=1
else
  say "Skipped. Emails will only work going to your Resend account email;"
  say "you can re-run this wizard after verifying the domain."
  DOMAIN_VERIFIED=0
fi

# ── Stage 3: API key ──────────────────────────────────────────────────────
stage "Resend — create an API key"
open_url "https://resend.com/api-keys"
step "Click 'Create API Key' → name it (e.g. 'house-scheduler') →"
step "Permission: 'Sending access' is enough → Create."
step "Copy the key — it starts with 're_' and is shown ONCE."
ask_secret RESEND_API_KEY "Paste the API key (hidden input):"
until [[ "$RESEND_API_KEY" =~ ^re_ ]]; do
  warn "That doesn't look like a Resend key (expected to start with re_)."
  confirm "Use it anyway?" && break
  ask_secret RESEND_API_KEY "Paste the API key (hidden input):"
done

# ── Stage 4: push the key to the worker + local .env ──────────────────────
stage "Worker — store RESEND_API_KEY"
say "Storing the key on the Cloudflare worker and in local .env."
put_worker_secret RESEND_API_KEY "$RESEND_API_KEY"
write_env RESEND_API_KEY "$RESEND_API_KEY"
pause "Press Enter to continue"

# ── Stage 5: sender address ───────────────────────────────────────────────
stage "Email — sender address (EMAIL_FROM)"
if [[ "${DOMAIN_VERIFIED:-0}" == "1" ]]; then
  say "Domain is verified, so you can send from any address at $DOMAIN."
  say "Suggested: House Scheduler <scheduler@$DOMAIN>"
  ask EMAIL_FROM "Sender (Enter = suggested): "
  if [[ -z "$EMAIL_FROM" ]]; then
    EMAIL_FROM="House Scheduler <scheduler@$DOMAIN>"
  fi
  put_worker_secret EMAIL_FROM "$EMAIL_FROM"
  write_env EMAIL_FROM "$EMAIL_FROM"
else
  say "Domain not verified, so leave EMAIL_FROM as the default"
  say "'House Scheduler <onboarding@resend.dev>' — sends will only reach"
  say "your Resend account's own address. Re-run this wizard after"
  say "verifying the domain to switch to a real sender."
  note "Current local value: $( _existing EMAIL_FROM || echo unset )"
fi

# ── Stage 6: verify end to end ────────────────────────────────────────────
stage "Verify — send a real notification"
say "Submitting a test request to the live site; the admin notification"
say "should arrive at $ADMIN_EMAIL."
TEST_DATE=$(date -d "+7 days" +%Y-%m-%d)
RESP=$(curl -s --max-time 30 \
  -H "content-type: application/json" \
  -d "{\"name\":\"Resend Setup Test\",\"email\":\"$ADMIN_EMAIL\",\"roomIds\":[1],\"dates\":[\"$TEST_DATE\"],\"note\":\"Sent by setup-resend wizard — safe to withdraw.\"}" \
  "https://beachroad.casa/api/requests" || true)
say "Response: $RESP"
if printf '%s' "$RESP" | grep -q '"emailQueued":true'; then
  say "✓ Resend accepted the email — check your inbox (and spam)."
else
  warn "emailQueued is false — Resend rejected it. Watch it live:"
  note "  npx wrangler tail vineyard-scheduler   # then resubmit a request"
  note "A '[mailer] ...' log line states the exact reason (bad key,"
  note "unverified sender, ...). Fix, then submit another request."
fi
CANCEL_URL=$(printf '%s' "$RESP" | grep -o 'https://[^"]*/api/cancel/[^"]*' || true)
if [[ -n "$CANCEL_URL" ]]; then
  note "Withdraw the test request when done: $CANCEL_URL"
fi
say "All done — emails now notify $ADMIN_EMAIL on every new request."
# ──────────────────────────────────────────────────────────────────────────

finish
